version: '3'
services:
  backend:
    build: ./app
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/usr/src/app
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb+srv://bot:bot123@cluster0.xph5e.mongodb.net/feature-hunt?retryWrites=true&w=majority
      #- DB=mongodb://mongodb:27017/todoDev

  frontend:
    image: node:alpine
    build: ./feature-hunt-frontend
    ports:
      - 4000:4000
    # working_dir: /srv/app
    # volumes:
    #   - type: bind
    #     source: ./feature-hunt-frontend
    #     target: /srv/app
    tty: true
  # frontend:
  #   build: .
  #   volumes:
  #     - ./src:/usr/src/app/src
  #     - ./public:/usr/src/app/public
  #     - ./test:/usr/src/app/test
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true

networks:
  default:
    name: feature_hunt
