on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        cache: 'npm'

     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2

     - name: script
       run: |
         npm install
         npm install coveralls
         npm test -- --coverage
     - name: Coveralls
       uses: coverallsapp/github-action@v1.1.2
       with:
         github-token: ${{ github.token }}
         #path-to-lcov: cat ./coverage/lcov.info | node node_modules/.bin/coveralls
