  name: Assigned Issues Are In Progress

  on:
    issues:
      types: [assigned]

  jobs:
    move-to-in-progress:
      runs-on: ubuntu-latest
      name: Move to In Progress Column
      steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Move to In Progress
        uses: kin/gh-action-move-issue-to-column@1.0
        with:
          access-token: "#{{ secrets.GITHUB_TOKEN }}"
          project-name: "Roadmap"
          target-column: "In progress"

  name: Unassigned Issues Are To Do

  on:
    issues:
      types: [unassigned]

  jobs:
    move-to-to-do:
      runs-on: ubuntu-latest
      name: Move to To Do Column
      steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Move to To Do
        uses: kin/gh-action-move-issue-to-column@1.0
        with:
          access-token: "#{{ secrets.GITHUB_TOKEN }}"
          project-name: "Roadmap"
          target-column: "To do"

